intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libzydis%lib{zydis}
import intf_libs += xxhash%lib{xxhash}

lib{iw4x-utility}: {hxx ixx txx cxx}{** -{utility-win32 config version}} \
                   {hxx            }{                   config version } \
                   {def            }{**                                } \
                   $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest
hxx{config}:  in{config}

tsys    = $cxx.target.system
tclass  = $cxx.target.class
windows = ($tclass == 'windows')
mingw32 = ($tsys == 'mingw32')

ws2_32 =
if ($mingw32)
  ws2_32 += -lws2_32
else
  ws2_32 += ws2_32.lib

# Only include utility-win32.hxx when targeting Windows.
#
lib{iw4x-utility}: {hxx}{utility-win32}: include = $windows

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.libs =+ $ws2_32

obja{*}: cxx.poptions += -DLIBIW4X_UTILITY_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_UTILITY_SHARED_BUILD

# Export options.
#

lib{iw4x-utility}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs $ws2_32
}

liba{iw4x-utility}: cxx.export.poptions += -DLIBIW4X_UTILITY_STATIC
libs{iw4x-utility}: cxx.export.poptions += -DLIBIW4X_UTILITY_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{iw4x-utility}: bin.lib.version = "-$version.project_id"
else
  lib{iw4x-utility}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libiw4x/utility/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/utility/
  install.subdirs = true
}
