# file      : buildfile
# license   : curl License; see accompanying COPYING file
#
./: {*/ -build/} doc{INSTALL README} legal{COPYING} manifest

# Don't install tests or the INSTALL file.
#
tests/:          install = false
doc{INSTALL}@./: install = false
