plat_libs = # Platform depencencies.

switch $cxx.target.class, $cxx.target.system
{
  case 'windows', 'mingw32'
    plat_libs += -lws2_32

  case 'windows'
    plat_libs += ws2_32.lib
}

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libquill%lib{quill}
import intf_libs += libzydis%lib{zydis}

lib{iw4x}: {hxx ixx txx cxx}{** -version} \
           {hxx            }{    version} \
           {def            }{**         } \
           $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions += "-I$out_root" "-I$src_root"
cxx.libs += $plat_libs

if ($config.libiw4x.develop)
  cxx.poptions += "-DLIBIW4X_DEVELOP"

# Shared headers.
#
if ($cxx.class == 'gcc')
  cxx.poptions += "-include" "$src_root/libiw4x/utility.hxx"       \
                  "-include" "$src_root/libiw4x/utility-win32.hxx"

obja{*}: cxx.poptions += -DLIBIW4X_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_SHARED_BUILD

# Export options.
#
lib{iw4x}: bin.lib.prefix = "lib"
lib{iw4x}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs $plat_libs
}

# Export shared headers.
#
if ($cxx.class == 'gcc')
  lib{iw4x}: \
    cxx.export.poptions += "-include" "$src_root/libiw4x/utility.hxx"       \
                           "-include" "$src_root/libiw4x/utility-win32.hxx"

liba{iw4x}: cxx.export.poptions += -DLIBIW4X_STATIC
libs{iw4x}: cxx.export.poptions += -DLIBIW4X_SHARED

# Install into the libiw4x/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/
  install.subdirs = true
}
