import! nasm = nasm%exe{nasm}

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import? intf_libs += libcpptrace%lib{cpptrace}
import  intf_libs += libzydis%lib{zydis}
import  intf_libs += libboost-asio%lib{boost_asio}
import  intf_libs += libboost-dll%lib{boost_dll}
import  intf_libs += libimgui%lib{imgui}

lib{iw4x}: {hxx ixx txx cxx}{** -version -iw4x-options} \
           {hxx            }{    version              } \
           {def            }{**                       } \
           {cli.cxx        }{             iw4x-options} \
           $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

cli.cxx{iw4x-options}: cli{iw4x}

cli.options = --cli-namespace iw4x::cli

# There is no built-in rule to synthesize the lib{s,a} -> obj{s,a} -> asm{}
# dependencies so we have to do it manually.
#
for n: oob/init
{
  libs{iw4x}: objs{$(n).asm.so.o}
  liba{iw4x}: obja{$(n).asm.a.o}

  objs{$(n).asm.so.o}: file{$(n).asm} $nasm
  {{
    diag nasm ($<[0])
    $nasm -f win64 -o $path($>) $path($<[0])
  }}

  obja{$(n).asm.a.o}: file{$(n).asm} $nasm
  {{
    diag nasm ($<[0])
    $nasm -f win64 -o $path($>) $path($<[0])
  }}
}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

if ($config.libiw4x.develop)
  cxx.poptions += "-DLIBIW4X_DEVELOP"

if ($config.libiw4x.cpptrace)
  cxx.poptions += "-DLIBIW4X_CPPTRACE"

obja{*}: cxx.poptions += -DLIBIW4X_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBIW4X_SHARED_BUILD

# Export options.
#
lib{iw4x}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{iw4x}: cxx.export.poptions += -DLIBIW4X_STATIC
libs{iw4x}: cxx.export.poptions += -DLIBIW4X_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
# if $version.pre_release
#   lib{iw4x}: bin.lib.version = "-$version.project_id"
# else
#   lib{iw4x}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libiw4x/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libiw4x/
  install.subdirs = true
}
